### ISSUE TITLE
feat(strategy): liquid exchange as a Portfolio strategy

### ISSUE THREAD

**Issue by Autoparallel** [primitivefinance/excalibur#184]
**Is your feature request related to a problem? Please describe.**
I believe it would streamline our set up process as well as agent abstractions if we had a liquid exchange hosted by Portfolio. 

<img width="1426" alt="image" src="https://github.com/primitivefinance/excalibur/assets/20118821/1874f3dc-6903-41a3-ac70-954595015c61">

On the setup phase, we can have a token admin create a list of tokens and a portfolio deployer can add all the respective pairs to portfolio. 

Pools can be spawned by the "admins" that are the `ParameterChanger`s for the pool. The `PriceChanger` can then become a type of `ParameterChanger`. The `WeightChanger` would also be one, and any `ParameterChanger` for RMM would also be a specific instance of one.

**Comment by 0xJepsen** [comment]
@Autoparallel and @kinrezC add some thoughts here
